[platformio]
src_dir = main
; 기본적으로 빌드할 환경을 지정합니다.
default_envs = esp32-s3-n16r8

[env]
; 올바른 PlatformIO 플랫폼 버전으로 수정 (ESP-IDF v5.5.3 자동 적용)
platform = espressif32 @ 6.13.0
framework = espidf
monitor_filters = direct
monitor_speed = 115200

[env:esp32-s3-n16r8]
board = esp32-s3-devkitc-1
board_build.partitions = partitions_example.csv

; S3 N16R8 하드웨어 사양
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
